import { Geist, Geist_Mono } from "next/font/google";

import { AuthProvider } from "@/contexts/authContext";
import { AppSidebar } from "@/components/commons/layout/AppSidebar";
import { SidebarProvider } from "@/components/ui/sidebar";
import { ThemeProvider } from "next-themes";

import Wrapper from "@/components/commons/layout/Wrapper";
import LayoutHeader from "@/components/commons/layout/LayoutHeader";

import type { Metadata } from "next";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
          <AuthProvider>
            <SidebarProvider defaultOpen={false}>
              <div className="flex flex-col w-full">
                <LayoutHeader />
                <main className="w-full flex-1">
                  <Wrapper>{children}</Wrapper>
                </main>
              </div>
              <AppSidebar />
            </SidebarProvider>
          </AuthProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
